# SPDX-FileCopyrightText: 2006-2023, Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2023, Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC0-1.0
name: "MacOS"
description: "Standardized building for IV projects"

env:
  TZ: Europe/Berlin

inputs:
  compiler:
    description: "which compiler to use \"gcc12-cpp20-release\", \"clang16-cpp17-debug\", etc"
    required: true
  cmake_flags:
    description: "additional cmake flags"
    required: false
    default: ""
  threads:
    description: "number of threads to use"
    required: false
    default: 1
runs:
  using: 'composite'
  steps:
   - name: Checkout Repo
     uses: actions/checkout@v4
     with:
       path: repo
       submodules: recursive
   - name: Install tools
     shell: bash
     run: |
        echo \"${GITHUB_ACTION}\" \"${GITHUB_REF}\" \"${GITHUB_BASE_REF}\" \"${GITHUB_RUN_NUMBER}\"
        echo 'eval "$(brew shellenv)"' > env.sh
        echo "Setup for " ${{ inputs.compiler }}
        echo "export CXX_STANDARD=20" >> env.sh
        echo "export BUILD_TYPE=Release" >> env.sh
        echo "export CMAKE_CXX_FLAGS=" >> env.sh
        echo "export CMAKE_C_FLAGS=" >> env.sh

        brew update-reset
        brew install --force-bottle --overwrite cmake pkg-config bash

   - name: Setup gcc 11
     if: ${{ startsWith(inputs.compiler, 'gcc11-') || (inputs.compiler == 'gcc11') }}
     shell: bash
     run: |
       source env.sh
       brew install --force-bottle gcc@11
       brew link -f gcc@11
       echo "export CXX=g++-11" >> env.sh

   - name: Setup gcc 12
     if: ${{ startsWith(inputs.compiler, 'gcc12-') || (inputs.compiler == 'gcc12') }}
     shell: bash
     run: |
       source env.sh
       brew install --force-bottle gcc@12
       brew link -f gcc@12
       echo "export CXX=g++-12" >> env.sh

   - name: Setup gcc 13
     if: ${{ startsWith(inputs.compiler, 'gcc13-') || (inputs.compiler == 'gcc13') }}
     shell: bash
     run: |
       source env.sh
       brew install --force-bottle gcc@13
       brew link -f gcc@13
       echo "export CXX=g++-13" >> env.sh

   - name: Setup clang 15
     if: ${{ startsWith(inputs.compiler, 'clang15-') || (inputs.compiler == 'clang15') }}
     shell: bash
     run: |
       source env.sh
       brew install --force-bottle llvm@15
       brew link -f llvm@15
       echo "export CXX=clang++" >> env.sh
       INSTALL_PREFIX=$(brew --prefix llvm@15)
       echo "export PATH=\"${INSTALL_PREFIX}/bin:$PATH\"" >> env.sh
       echo "export LDFLAGS=\"-L${INSTALL_PREFIX}/lib/c++ -Wl,-rpath,${INSTALL_PREFIX}/lib/c++\"" >> env.sh

   - name: Setup clang 16
     if: ${{ startsWith(inputs.compiler, 'clang16-') || (inputs.compiler == 'clang16') }}
     shell: bash
     run: |
       source env.sh
       brew install --force-bottle llvm@16
       brew link -f llvm@16
       echo "export CXX=clang++" >> env.sh
       INSTALL_PREFIX=$(brew --prefix llvm@16)
       echo "export PATH=\"${INSTALL_PREFIX}/bin:$PATH\"" >> env.sh
       echo "export LDFLAGS=\"-L${INSTALL_PREFIX}/lib/c++ -Wl,-rpath,${INSTALL_PREFIX}/lib/c++\"" >> env.sh

   - name: Setup clang 17
     if: ${{ startsWith(inputs.compiler, 'clang17-') || (inputs.compiler == 'clang17') }}
     shell: bash
     run: |
       source env.sh
       brew install --force-bottle llvm@17
       brew link -f llvm@17
       echo "export CXX=clang++" >> env.sh
       INSTALL_PREFIX=$(brew --prefix llvm@17)
       echo "export PATH=\"${INSTALL_PREFIX}/bin:$PATH\"" >> env.sh
       echo "export LDFLAGS=\"-L${INSTALL_PREFIX}/lib/c++ -Wl,-rpath,${INSTALL_PREFIX}/lib/c++\"" >> env.sh

   - name: Setup c++17
     if: ${{ endsWith(inputs.compiler, '-cpp17') || contains(inputs.compiler, '-cpp17-') }}
     shell: bash
     run: |
       echo "export CXX_STANDARD=17" >> env.sh

   - name: Setup c++20
     if: ${{ endsWith(inputs.compiler, '-cpp20') || contains(inputs.compiler, '-cpp20-') }}
     shell: bash
     run: |
       echo "export CXX_STANDARD=20" >> env.sh

   - name: Setup c++23
     if: ${{ endsWith(inputs.compiler, '-cpp23') || contains(inputs.compiler, '-cpp23-') }}
     shell: bash
     run: |
       echo "export CXX_STANDARD=23" >> env.sh


   - name: Setup release
     if: ${{ endsWith(inputs.compiler, '-release') || contains(inputs.compiler, '-release-') }}
     shell: bash
     run: |
       echo "export BUILD_TYPE=Release" >> env.sh

   - name: Setup Debug
     if: ${{ endsWith(inputs.compiler, '-debug') || contains(inputs.compiler, '-debug-') }}
     shell: bash
     run: |
       echo "export BUILD_TYPE=Debug" >> env.sh
       echo 'export CMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} -fno-omit-frame-pointer"' >> env.sh
       echo 'export CMAKE_C_FLAGS="${CMAKE_C_FLAGS} -fno-omit-frame-pointer"' >> env.sh

   - name: Setup Strict
     if: ${{ endsWith(inputs.compiler, '-strict') || contains(inputs.compiler, '-strict-') }}
     shell: bash
     run: |
       echo 'export CMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} -Wall -Werror -Wpedantic -Wextra"' >> env.sh
       echo 'export CMAKE_C_FLAGS="${CMAKE_C_FLAGS} -Wall -Werror -Wpedantic -Wextra"' >> env.sh

   - name: Setup Sanitize Address
     if: ${{ endsWith(inputs.compiler, '-sanitize_address') || contains(inputs.compiler, '-sanitize_address-') }}
     shell: bash
     run: |
       echo 'export CMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} -fsanitize=address"' >> env.sh
       echo 'export CMAKE_C_FLAGS="${CMAKE_C_FLAGS} -fsanitize=address"' >> env.sh

   - name: Setup Sanitize Undefined Behavior
     if: ${{ endsWith(inputs.compiler, '-sanitize_undefined') || contains(inputs.compiler, '-sanitize_undefined-') }}
     shell: bash
     run: |
       echo 'export CMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} -fsanitize=undefined"' >> env.sh
       echo 'export CMAKE_C_FLAGS="${CMAKE_C_FLAGS} -fsanitize=undefined"' >> env.sh

   - name: Tool versions
     shell: bash
     run: |
       source env.sh
       cmake --version
       ${CXX} --version
   - name: Configure tests
     shell: bash
     run: |
       source env.sh
       mkdir build && cd $_
       cmake ../repo -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_CXX_STANDARD=${CXX_STANDARD} ${{ inputs.cmake_flags }} -DCMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS:-}" -DCMAKE_C_FLAGS="${CMAKE_C_FLAGS:-}"
   - name: Build tests
     shell: bash
     run: |
       source env.sh
       cd build
       make -k -j ${{ inputs.threads }} VERBOSE=1
   - name: Run tests
     shell: bash
     run: |
       source env.sh
       cd build
       ctest . -j ${{ inputs.threads }} --output-on-failure ${CTEST_TIMEOUT+--timeout ${CTEST_TIMEOUT}} || ctest . -j ${{ inputs.threads }} --output-on-failure ${CTEST_TIMEOUT+--timeout ${CTEST_TIMEOUT}} --rerun-failed
